Repository wecode-bootcamp-korea/30-2nd-YourHomeIsMine-frontend, pull requests merged in 2022-03, with the labels that each got.

#2 [30기 정수인] [style-component]Modify: styled-component 수정 완료 npm 확인
  package-lock.json
  package.json
  src/index.js
  src/styles/GlobalStyle.js
  src/styles/fonts/NotoSansKR-Black.woff
  src/styles/fonts/NotoSansKR-Bold.woff
  src/styles/fonts/NotoSansKR-Light.woff
  src/styles/fonts/NotoSansKR-Medium.woff
  src/styles/fonts/NotoSansKR-Regular.woff
  src/styles/fonts/NotoSansKR-Thin.woff
  src/styles/fonts/fonts.js
  src/styles/theme.js
Labels: Status: 리뷰 요청

#5 [30기 신윤숙] Modify: Nav 수정 완료
  .vscode/settings.json
  src/component/Nav/Nav.js
  src/component/Nav/Nav.scss
Labels: Status: Accepted, Status: 추가 기능 구현중, Status: 수정 요청

#4 [30기 정수인] [Detail] Modify: 기능 구현 완료!
  package-lock.json
  package.json
  public/data/AmenitiesList.json
  public/data/DetailData.json
  public/data/HouseImg.json
  public/data/HouseSubDataList.json
  public/data/UserReview.json
  public/data/totalReview.json
  public/images/calendar.png
  public/images/door.png
  public/images/enter.png
  public/images/house.png
  public/images/love.png
  public/images/medal.png
  public/images/nextBtn.png
  public/images/prevBtn.png
  public/images/selfCheck.png
  public/images/send.png
  public/images/star.png
  public/images/time.png
  public/index.html
  src/Router.js
  src/assets/images/down.png
  src/assets/images/up.png
  src/index.js
  src/pages/Detail/AmenitiesCard.js
  src/pages/Detail/Calender.js
  src/pages/Detail/Detail.js
  src/pages/Detail/IconText.js
  src/pages/Detail/Modal.js
  src/pages/Detail/ReservationBar.js
  src/pages/Detail/ReviewCard.js
  src/pages/Detail/Rules.js
  src/pages/Detail/StarReview.js
Labels: Status: 리뷰 요청

#3 [30기 이상민] [List page] Filter 구현완료. 모달창 구현완료
  package-lock.json
  package.json
  public/data/data.js
  public/data/data.json
  public/data/houseType.json
  src/Router.js
  src/config.js
  src/pages/Detail/StarReview.js
  src/pages/List/Card/Card.js
  src/pages/List/Category.js
  src/pages/List/Counter.js
  src/pages/List/Date.js
  src/pages/List/DateModal.js
  src/pages/List/GuestModal.js
  src/pages/List/List.js
  src/pages/List/List.scss
  src/pages/List/Slide.js
Labels: Status: 수정 요청

#6 [30기 신윤숙] [Modify] Login Complete
  public/images/image.js
  public/images/kakao_login_btn.png
  public/index.html
  src/Router.js
  src/component/Nav/Nav.js
  src/pages/Login/KakaoLogin.js
  src/pages/Login/KakaoLogin.scss
  src/pages/Login/Login.js
  src/pages/Login/Login.scss
Labels: Status: 리뷰 요청

#9 Add: 메인페이지 완료!
  public/data/MainContent.json
  src/pages/Main/Main.js
Labels: Status: 리뷰 요청
